version: 0.2

phases:
  install:
    commands:
      - echo "No installation needed for static HTML site"

  build:
    commands:
      - echo "Building static HTML site..."
      - mkdir -p output
      - rsync -av --exclude='output' ./ output/

  post_build:
    commands:
      - echo "Build completed. Files in output directory:"
      - ls -la output/
      - echo "Invalidating CloudFront cache..."

artifacts:
  files:
    - '**/*'
  base-directory: output