version: 0.2

phases:
  install:
    commands:
      - echo "No installation needed for static HTML"

  pre_build:
    commands:
      - echo "Preparing build..."

    build:
    commands:
      - echo "Building static HTML site"
      - mkdir -p output
      - rsync -av --exclude 'output' ./ output/
      - rm -f output/buildspec.yml

  post_build:
    commands:
      - echo "Build complete - $(ls -la output/)"
      - echo "Invalidating CloudFront cache..."

artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
